# Generated by Django 5.2.6 on 2025-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_lifestylemetrics_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='assessment_type',
            field=models.CharField(choices=[('manual', 'Manual Assessment'), ('automated', 'Automated Assessment'), ('llama_prediction', 'LLaMA AI Prediction'), ('rule_based', 'Rule-Based Assessment')], default='automated', help_text='Type of risk assessment performed', max_length=20),
        ),
    ]
